### PR TITLE
twrpdtgen: QoL changes

### PR DESCRIPTION
**Pull request by TriDiscord**
- Add Marvell Armanda support
- Change Python code readability
- Update copyright

### CODE REVIEW

**Comment by SebaUbuntu** [comment]
All useless changes
Plus as mentioned in the issue regarding mrvl, all of these are not used within bootable/recovery, thus they're useless when building a recovery

**Comment by TriDiscord** [comment]
"useless"?

They're not meant to be BIG overhauls or anything, as the title states, these are just QoL changes for making the code more readable. And I'm pretty sure the Marvell changes have 2 flags in them that are actually used.

**Comment by SebaUbuntu** [comment]
List the actually used flags then, you'll get one one day :D
Also you changed some stuff breaking Python rules (like running code on global scope, import inside functions, etc)
Stop trying to do random PR to get your commits merged (for flexing the fact that you got a commit merged here?), that's considered spam, next time it happens I'm gonna report you, you've been warned

**Comment by TriDiscord** [comment]
I'm not trying to "flex" or anything, what are you on about? I'm not making a random PR, this was supposed to be a commit for Marvell Armanda support AND basic Python changes.

If you think that me trying to change a few syntax things is "seeking for attention" and "trying to flex with having a commit merged", you might want to improve your social skills. No one's trying to be listed on your repository for the "cOoLnEsS".

**Pull request closed without merging**
